apiVersion: v1
kind: Secret
metadata:
  name: y-db-secret
data:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: y-back-secret
data:
  SECRET_KEY: ${SECRET_KEY}
