- op: add
  path: /spec/template/spec/containers/0/args/1
  value: --tcp-services-configmap=ingress-nginx/tcp-services
- op: add
  path: /spec/template/spec/containers/0/ports/0
  value: 
    name: tcp-postgres
    containerPort: ${POSTGRES_PORT}
    hostPort: ${POSTGRES_PORT}
    protocol: TCP
